version: "3.4"
services:
  MSSQLDataBase:
    container_name: MSSQLDataBase
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=msSQL123
    ports:
      - "1337:1433"
    volumes:
      - ./REA.mssql_data:/data:/var/opt/mssql/data
      - ./REA.mssql_data:/log:/var/opt/mssql/log
      - ./REA.mssql_data:/secrets:/var/opt/mssql/secrets

  MongoDataBase:
    container_name: MongoDataBase
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./REA.mongo_data:/data/db


  RedisDataBase:
    container_name: RedisDataBase
    image: redis
    ports:
      - "1335:6379"

  RabbitMQ:
    container_name: RabbitMQ
    tty: true
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "1334:5672"
      - "5672:5672"
      - "15672:15672"

  ElasticSearch:
    container_name: ElasticSearch
    image: elasticsearch:7.16.1
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
    ports:
      - "9200:9200"

  Kibana:
    container_name: Kibana
    image: kibana:7.16.1
    depends_on:
      - ElasticSearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200/
    ports:
      - "5601:5601"